### ISSUE TITLE
Self-hosting versioning

### ISSUE THREAD

**Issue by n1ru4l** [graphql-hive/platform#2995]
We should follow the following release format for docker images, inspired by minio https://hub.docker.com/r/minio/minio/tags

`RELEASE.2023-09-30T07-02-29Z`

Every release should have a corresponding release changelog on `docs.graphql-hive.com/changelog-self-hosted/<release-tag>`.
The page will contain all the necessary information for upgrading to this version from the last version.

Releases are made from deployed versions that we have already tested in production.

**Comment by n1ru4l** [comment]
We also need to think on how we can communicate hive/cli <-> hive self-hosted version compatability.

**Comment by Elyytscha** [comment]
i dont think minio versioning is state of the art, sane tagging should look like this:

when graphql hive version 1.4.3 (semver) is built, push the following images:

docs.graphql-hive.com/hive-server:1
docs.graphql-hive.com/hive-server:1.4
docs.graphql-hive.com/hive-server:1.4.3
docs.graphql-hive.com/hive-server:latest
docs.graphql-hive.com/hive-server:stable

https://semver.org/lang/de/

**Comment by Elyytscha** [comment]
i mean because you downvoted, i just wanted to highlight whats my issue with the minio versioning.

devops/sre/platform engineers like to upgrade their systems automated, if they can rely on semantic versioning, they can ensure that they dont ship unwanted major/breaking change upgrades automated, so basically they can choose if they are upgrading on patchlevel, feature level or even major/breaking change level, when the application is known for handling major upgrades automated without problems.

if the versioning is simply RELEASE.2023-09-30T07-02-29Z

we have absolutely no idea if we can ship this release automated into production, we have to read the changelogs first.

**Comment by platzhersh** [comment]
Second @Elyytscha 's input.

We currently fixed the versions for our self-hosting and we are not really looking forward to the first time we will update to newer images, since we won't really know what all the incoming changes will be without going through all the commits since the version we currently have deployed.

For our own projects we are also following semver versioning based on conventional commits.

**Comment by Elyytscha** [comment]
> Second @Elyytscha 's input.
> 
> We currently fixed the versions for our self-hosting and we are not really looking forward to the first time we will update to newer images, since we won't really know what all the incoming changes will be without going through all the commits since the version we currently have deployed.
> 
> For our own projects we are also following semver versioning based on conventional commits.

I mean that should be the job of cicd and conventional commits(enforce conventional commits, auto generate changelogs tags and releases and then build the images with the spit out tags), thats nothing someone has to do by hand

**Comment by kamilkisiela** [comment]
![image](https://github.com/user-attachments/assets/5b68777e-1248-4b17-a8a3-da91bb496a4f)

As of today, we can offer precise versions

```
ghcr.io/graphql-hive/server:1.2.3
```

You can read about it here: https://the-guild.dev/graphql/hive/product-updates/2024-10-29-versioning-for-self-hosters

---

We don't support major or minor version matching labels. I hope we will some day, but it's low priority at the moment.

```
ghcr.io/graphql-hive/server:1
ghcr.io/graphql-hive/server:1.2
```
